/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WeightsRouteImport } from './routes/weights'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as SettingsProfileRouteImport } from './routes/settings_.profile'
import { Route as DesignScreensRouteImport } from './routes/design.screens'
import { Route as DesignOnboardingRouteImport } from './routes/design.onboarding'
import { Route as DesignLanguageRouteImport } from './routes/design.language'
import { Route as DesignComponentsRouteImport } from './routes/design.components'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightsRoute = WeightsRouteImport.update({
  id: '/weights',
  path: '/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignRoute,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings_/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignScreensRoute = DesignScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => DesignRoute,
} as any)
const DesignOnboardingRoute = DesignOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DesignRoute,
} as any)
const DesignLanguageRoute = DesignLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => DesignRoute,
} as any)
const DesignComponentsRoute = DesignComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DesignRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/weights': typeof WeightsRoute
  '/workouts': typeof WorkoutsRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/language': typeof DesignLanguageRoute
  '/design/onboarding': typeof DesignOnboardingRoute
  '/design/screens': typeof DesignScreensRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/design/': typeof DesignIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/weights': typeof WeightsRoute
  '/workouts': typeof WorkoutsRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/language': typeof DesignLanguageRoute
  '/design/onboarding': typeof DesignOnboardingRoute
  '/design/screens': typeof DesignScreensRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/design': typeof DesignIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/weights': typeof WeightsRoute
  '/workouts': typeof WorkoutsRoute
  '/design/components': typeof DesignComponentsRoute
  '/design/language': typeof DesignLanguageRoute
  '/design/onboarding': typeof DesignOnboardingRoute
  '/design/screens': typeof DesignScreensRoute
  '/settings_/profile': typeof SettingsProfileRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/design/': typeof DesignIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/weights'
    | '/workouts'
    | '/design/components'
    | '/design/language'
    | '/design/onboarding'
    | '/design/screens'
    | '/settings/profile'
    | '/workout/$id'
    | '/design/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/weights'
    | '/workouts'
    | '/design/components'
    | '/design/language'
    | '/design/onboarding'
    | '/design/screens'
    | '/settings/profile'
    | '/workout/$id'
    | '/design'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/weights'
    | '/workouts'
    | '/design/components'
    | '/design/language'
    | '/design/onboarding'
    | '/design/screens'
    | '/settings_/profile'
    | '/workout/$id'
    | '/design/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  WeightsRoute: typeof WeightsRoute
  WorkoutsRoute: typeof WorkoutsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  WorkoutIdRoute: typeof WorkoutIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weights': {
      id: '/weights'
      path: '/weights'
      fullPath: '/weights'
      preLoaderRoute: typeof WeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof DesignRoute
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/profile': {
      id: '/settings_/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/screens': {
      id: '/design/screens'
      path: '/screens'
      fullPath: '/design/screens'
      preLoaderRoute: typeof DesignScreensRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/onboarding': {
      id: '/design/onboarding'
      path: '/onboarding'
      fullPath: '/design/onboarding'
      preLoaderRoute: typeof DesignOnboardingRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/language': {
      id: '/design/language'
      path: '/language'
      fullPath: '/design/language'
      preLoaderRoute: typeof DesignLanguageRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/components': {
      id: '/design/components'
      path: '/components'
      fullPath: '/design/components'
      preLoaderRoute: typeof DesignComponentsRouteImport
      parentRoute: typeof DesignRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DesignRouteChildren {
  DesignComponentsRoute: typeof DesignComponentsRoute
  DesignLanguageRoute: typeof DesignLanguageRoute
  DesignOnboardingRoute: typeof DesignOnboardingRoute
  DesignScreensRoute: typeof DesignScreensRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignComponentsRoute: DesignComponentsRoute,
  DesignLanguageRoute: DesignLanguageRoute,
  DesignOnboardingRoute: DesignOnboardingRoute,
  DesignScreensRoute: DesignScreensRoute,
  DesignIndexRoute: DesignIndexRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  WeightsRoute: WeightsRoute,
  WorkoutsRoute: WorkoutsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  WorkoutIdRoute: WorkoutIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
